rpc = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x03d2828c3d0800385d1463e5af693602da33c4b05b11a0a12152e0b5a778cd42"

[indexing]
contracts = [
  "erc20:0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7", # ETH fee token
  "erc20:0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d", # STRK fee token
]

[sql]
historical = [
  "untitled-Moves", 
  "untitled-DirectionsAvailable", 
  "untitled-Position", 
  "untitled-PositionCount",
  "untitled-Moved", 
  "untitled-Spawned", 
]

